// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllConfig() {
  return window['go']['backend']['App']['GetAllConfig']();
}

export function GetCurrentVersion() {
  return window['go']['backend']['App']['GetCurrentVersion']();
}

export function GetDocs() {
  return window['go']['backend']['App']['GetDocs']();
}

export function IsLinux() {
  return window['go']['backend']['App']['IsLinux']();
}

export function IsMac() {
  return window['go']['backend']['App']['IsMac']();
}

export function IsWindows() {
  return window['go']['backend']['App']['IsWindows']();
}

export function OpenAppDataPath() {
  return window['go']['backend']['App']['OpenAppDataPath']();
}

export function OpenDirectory(arg1) {
  return window['go']['backend']['App']['OpenDirectory'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['backend']['App']['OpenFile'](arg1);
}

export function OpenLogFile() {
  return window['go']['backend']['App']['OpenLogFile']();
}

export function UpdateCheck() {
  return window['go']['backend']['App']['UpdateCheck']();
}

export function UpdatePreferences(arg1) {
  return window['go']['backend']['App']['UpdatePreferences'](arg1);
}
