// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetAllConfig():Promise<backend.AllConfig>;

export function IsLinux():Promise<boolean>;

export function IsMac():Promise<boolean>;

export function IsWindows():Promise<boolean>;

export function OpenAppDataPath():Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenLogFile():Promise<void>;
