// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {Updater} from '../models';
import {Config} from '../models';

export function GetAllConfig():Promise<backend.AllConfig>;

export function GetCurrentVersion():Promise<string>;

export function GetDocs():Promise<backend.SurrealDocs>;

export function IsLinux():Promise<boolean>;

export function IsMac():Promise<boolean>;

export function IsWindows():Promise<boolean>;

export function OpenAppDataPath():Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenLogFile():Promise<void>;

export function UpdateCheck():Promise<Updater.UpdateInfo>;

export function UpdatePreferences(arg1:Config.Preferences):Promise<void>;
