// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['Config']['Connections']['Add'](arg1);
}

export function Remove(arg1) {
  return window['go']['Config']['Connections']['Remove'](arg1);
}

export function SetCurrent(arg1) {
  return window['go']['Config']['Connections']['SetCurrent'](arg1);
}

export function Setup() {
  return window['go']['Config']['Connections']['Setup']();
}

export function Update(arg1) {
  return window['go']['Config']['Connections']['Update'](arg1);
}
