// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {Config} from '../models';

export function Add(arg1:Config.Connection):Promise<Config.Connection>;

export function Remove(arg1:any):Promise<Config.Connections>;

export function SetCurrent(arg1:any):Promise<void>;

export function Setup():Promise<void>;

export function Update(arg1:Config.Connections):Promise<Config.Connections>;
