// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {Config} from '../models';

export function DeleteQuery(arg1:string):Promise<Array<Config.Query>>;

export function GetQueries(arg1:string):Promise<Array<Config.Query>>;

export function RemoveQueries(arg1:string):Promise<void>;

export function SaveQuery(arg1:Config.SaveQueryRequest):Promise<Config.Query>;

export function Setup():Promise<void>;

export function Update():Promise<Config.QueriesList>;
