// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteQuery(arg1) {
  return window['go']['Config']['QueriesList']['DeleteQuery'](arg1);
}

export function GetQueries(arg1) {
  return window['go']['Config']['QueriesList']['GetQueries'](arg1);
}

export function RemoveQueries(arg1) {
  return window['go']['Config']['QueriesList']['RemoveQueries'](arg1);
}

export function SaveQuery(arg1) {
  return window['go']['Config']['QueriesList']['SaveQuery'](arg1);
}

export function Setup() {
  return window['go']['Config']['QueriesList']['Setup']();
}

export function Update() {
  return window['go']['Config']['QueriesList']['Update']();
}
