// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CanSetDimensions():Promise<boolean>;

export function CanSetPosition():Promise<boolean>;

export function Set():Promise<void>;

export function Setup():Promise<void>;
