// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CanSetDimensions() {
  return window['go']['Config']['Window']['CanSetDimensions']();
}

export function CanSetPosition() {
  return window['go']['Config']['Window']['CanSetPosition']();
}

export function Set() {
  return window['go']['Config']['Window']['Set']();
}

export function Setup() {
  return window['go']['Config']['Window']['Setup']();
}
